export const OPERATOR_TOAST_TEXT = {
  syncFailed: "Gagal sinkronisasi data",
  loadFailed: "Gagal memuat data",
  saveFailed: "Gagal menyimpan data",
  deleteFailed: "Gagal menghapus data",
  processFailed: "Gagal memproses data",
  dataUpdated: "Data berhasil diperbarui",
  quotationLoadFailed: "Gagal memuat data penawaran",
  quotationPdfFailed: "Gagal mencetak PDF",
  quotationStatusUpdated: "Status dokumen berhasil diperbarui",
  quotationStatusFailed: "Gagal memperbarui status dokumen",
  travelOrderExistsRedirect: "Surat tugas sudah tersedia, mengalihkan ke halaman pratinjau.",
  travelOrderDateRequired: "Tanggal berangkat dan kembali wajib diisi",
  travelOrderDestinationRequired: "Tujuan wajib diisi",
  travelOrderPurposeRequired: "Maksud dan tujuan wajib diisi",
  travelOrderCreated: "Surat tugas berhasil dibuat",
  travelOrderCreateFailed: "Gagal membuat surat tugas",
  travelOrderLoadFailed: "Gagal memuat data surat tugas",
  travelOrderDownloadSuccess: "Surat tugas dan lampiran berhasil diunduh",
  pdfGenerateFailed: "Gagal membuat PDF",
} as const;

export const OPERATOR_EMPTY_TEXT = {
  dataNotFoundCaps: "Data Tidak Ditemukan",
  dataNotFound: "Data tidak ditemukan.",
  noActivity: "Belum ada riwayat aktivitas.",
  noAssistant: "Belum ada data asisten",
  noContact: "Tidak ada kontak",
  noCategory: "Tidak ada kategori",
  noCategoryRegistered: "Belum ada kategori yang terdaftar",
  noService: "Tidak ada layanan",
  noServiceRegistered: "Belum ada layanan yang terdaftar",
  noBill: "Belum ada tagihan",
  quotationNotFound: "Dokumen tidak ditemukan.",
  assignmentNotFound: "Assignment tidak ditemukan",
  travelOrderNotFound: "Surat tugas tidak ditemukan",
} as const;
